### ISSUE TITLE
Bug with decimal precision example

### ISSUE THREAD

**Issue by sergii** [wasabigeek/railshelp#12]
https://rails.help provides wrong example:

```
bin/rails g model ExampleModel other_model:references{polymorphic}:uniq lng:decimal{10,6}
```
right example:

```
bin/rails g model ExampleModel other_model:references{polymorphic}:uniq lng:decimal{10-6}
```

Please change `decimal{10,6}` to `decimal{10-6}`

**Comment by wasabigeek** [comment]
Thanks for bringing this up @sergii! This is actually what the [docs recommend](https://github.com/rails/rails/blob/a39cd44dcf1fe05ad7fc09914586888c76dc3cf8/activerecord/lib/rails/generators/active_record/model/USAGE#L68). I think it might have something to do with the shell https://github.com/rails/rails/issues/13520#issuecomment-370100231 (mine does the same too, for what it's worth).

**Comment by wasabigeek** [comment]
Added a note about this in https://github.com/wasabigeek/railshelp/commit/49188ee2bbbd3b4e688d18acbc295d118376cfc0.
